#-------------------------------
# General Site Settings
title: SuBin Seo 
logo: logo.svg 
description: Subin Seo's portfolio website


#-------------------------------
# Author Settings
author:
  name: Subin Seo 
  image: profile.png
  say-hello: Hello, I'm <strong>Subin Seo.</strong>
  bio: I am an MLIS(Master of Library and Information Science) student at the University of Maryland, College Park. My research interests began with <b>information behavior</b>, and more recently, I have been particularly interested in how <b>information systems</b> work and interact with humans. This has led to a growing interest in <r>AI, Search Engines, or Future Information Systems</r>. <br><br> <y>subinseo@umd.edu</y>